image: node:20.13.1

stages:
  - prepare
  - build
  - test
  - deploy

prepare:
  stage: prepare
  script:
    - npm install
    - npm install typescript --save-dev

build:
  stage: build
  script:
    - npm install
    - ls node_modules/.bin
    - npm run build

test:
  image: node:20.13.1
  stage: test
  script:
    - npm install
    - npm run test

deploy:
  image: node:20.13.1
  stage: deploy
  script:
    - npm install -g serve
    - serve -s build &
    - echo "Web application is deployed"
