image: node:22.9.0

stages:
  - prepare
  - build
  - test
  - deploy

prepare_job:
  stage: prepare
  script:
    - npm install
    - npm install --save-dev typescript

build_job:
  stage: build
  script: 
    - npm run build

test_job:
  stage: test
  script:
    - npm run test

deploy_job:
  image: node:22.9.0
  stage: deploy
  script:
    - npm install -g serve
    - serve -s build

